# Generated by Django 2.1.2 on 2018-10-11 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 10, 11, 4, 25, 26, 833848, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
