# Generated by Django 2.1.2 on 2018-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=150, verbose_name='Телефон')),
                ('address', models.TextField(max_length=150, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=70)),
                ('skype', models.TextField(max_length=150)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contacts',
            },
        ),
    ]
